### ISSUE TITLE
Dark User stylesheet as an option ?

### ISSUE THREAD

**Issue by MentalGear** [rileyjshaw/reduce-background-flicker#1]
Couldn't the suggested augmentation of using a custom user stylesheet not be added as a option to the extension ?
https://code.google.com/p/chromium/issues/detail?id=1373#c261

**Comment by rileyjshaw** [comment]
Definitely! From the readme:

> For the real Lords of Darkness out there, setting a custom user stylesheet to your preferred color will probably be more effective than this extension. The same trick applies to Firefox.

Extensions can't control user stylesheets, so that's something you'll have to set for yourself : )
